from tkinter import *
fenetre = Tk()
fenetre.title("anti stress")
fenetre.geometry("420x420")
cadre1 = Frame(fenetre)
cadre1.pack()
bouton1 = Button (fenetre, text = "start")
bouton1.pack()
bouton2 = Button (fenetre, text = "menu")
bouton2.pack()
bouton3 = Button (fenetre, text = "exit")
bouton3.pack()
entrée1 = Entry (fenetre)
entrée1.pack()
case_cocher1 = Checkbutton (fenetre, text = "coche moi")
case_cocher2 = Checkbutton (fenetre, text = "ou coche moi")
case_cocher3 = Checkbutton (fenetre, text = "ou alors coche moi")
case_cocher1.pack()
case_cocher2.pack()
case_cocher3.pack()
liste1 = Listbox (fenetre)
liste1.insert(1, "clique ici")
liste1.insert(2, "ou clique là")
liste1.insert(3, "ou clique par là")
liste1.insert(4, "ou clique par ici2")
liste1.pack()
menu1 = Menu(fenetre)
menu1.add_cascade(label="ici")
menu1.add_cascade(label="là")
menu1.add_cascade(label=":)")
fenetre.config(menu = menu1)
fenetre.mainloop()



